### ISSUE TITLE
From dosbox-x : use overlay file when its newer than zips

### ISSUE THREAD

**Issue by thesnable** [icculus/physfs#18]
Hi!

A very discrete problem:
i have a zip of an dos game. This is mounted via dosboxx via physfs overlay.
In this archive there is an file "sndcfg.ini". I need to replace this file while using the overlay. This is not possible. This the old file from the archive is used, although there is the new sndcfg.ini in the overlay part.

wish: in doubt use the overlays file (when its newer etc)

marco

**Comment by NebularNerd** [comment]
Seconding this request, the ability for the overlay to see newer versions of the file would be a great helps.

**Comment by icculus** [comment]
If the overlay is mounted earlier in the search path, it should override the .zip file's version (and function as an "overlay" would be expected to). Is this not the case?

**Comment by NebularNerd** [comment]
With [dosbox-x](https://github.com/joncampbell123/dosbox-x) you have to mount the .zip then the overlay otherwise it throws up an error. Any totally new files are ok with changes being reflected as things should. However files that exist inside the zip then subsequently modified are not picked up. Not sure if this is due to a specific implementation of how DosBox-x uses PhyFS or an issue with the library. It's briefly discussed in joncampbell123/dosbox-x#3355  

![command_001](https://user-images.githubusercontent.com/8470449/189187353-3bed230c-d018-470a-9ebb-e6d6ded5469a.png)

**Comment by icculus** [comment]
https://github.com/joncampbell123/dosbox-x/blob/3b002fa724a67b3cf26d5030391cbf3d5dea90a0/src/dos/drive_physfs.cpp#L371

Make that `1` a `0` so the overlay gets checked for files before the thing it overlays.

**Comment by icculus** [comment]
(Closing this under the assumption this isn't a PhysicsFS bug, but if there's more information later, please don't hesitate to mention it and we can reopen the bug.)
