### ISSUE TITLE
Your archive format

### ISSUE THREAD

**Issue by Quarnion** [icculus/physfs#50]
Hello, I would like to clarify whether it is possible to create your own archive format using the library?

If so, could you briefly explain what procedures need to be performed?

**Comment by Quarnion** [comment]
I read about _PHYSFS_Archiver_ but did not understand anything :(

**Comment by Green-Sky** [comment]
roughly speaking, you need to provide all the functions for your archive type.
i did this some years ago to load stringliterals (static c strings) as files.
https://github.com/MadeOfJelly/MushMachine/blob/master/framework/filesystem/src/mm/fs_const_archiver.hpp
(and .cpp in the same folder)

code is very hacky, you have been warned! :)

**Comment by icculus** [comment]
(Closing this because it's not a bug, but also: yes, you can provide your own archive format to PhysicsFS by supplying function pointers from your app without modifying PhysicsFS source code directly...but if it's a reasonably standard or popular format, it makes sense to just slot it into PhysicsFS's sources for others to use, too. Either approach is totally okay.)
